🚮 [DO_NOT_MERGE] Remove RENDLE_ON_IDLE experiment logic
ampproject/amphtml pull request #29661
Opened 2020-08-04 18:27 UTC by powerivq

Wait till https://github.com/ampproject/amphtml/pull/29660 rolls out and removes this experiment code for render-on-idle-fix.

2020-09-02 06:08 UTC, powerivq commented
need @lannka  to sign off the owner approval.

2020-09-08 16:49 UTC, lannka approved these changes

2020-09-08 17:26 UTC, powerivq commented
@jridgewell for owner approval. (this change was originally from choumx@)

2020-09-08 22:15 UTC, jridgewell approved these changes

2020-09-08 22:15 UTC, jridgewell requested changes

2020-09-08 22:15 UTC, jridgewell commented on build-system/global-configs/prod-config.json
> +  "ad-adsense-gam-round-params": 0.1
Is this intentional?

2020-09-08 22:22 UTC, powerivq commented on build-system/global-configs/prod-config.json
> +  "ad-adsense-gam-round-params": 0.1
great catch!

2020-09-08 22:36 UTC, jridgewell approved these changes

2020-09-10 22:43 UTC, merged