✨ Add amp-adplayer-pro
ampproject/amphtml pull request #29892
Opened 2020-08-19 08:40 UTC by adp-developer

An amp-adplayer-pro displays the video player by [AdPlayer.Pro](https://adplayer.pro/)

2020-08-19 14:26 UTC, honeybadgerdontcare commented on extensions/amp-adplayer-pro/validator-amp-adplayer-pro.protoascii
> +    requires_usage: EXEMPTED
please remove this line

2020-08-19 14:26 UTC, honeybadgerdontcare commented on extensions/amp-adplayer-pro/validator-amp-adplayer-pro.protoascii
> +    deprecated_allow_duplicates: true
please remove this line

2020-08-19 14:27 UTC, honeybadgerdontcare commented
@alanorozco fyi

2020-08-26 21:04 UTC, jridgewell commented
Sending this to @ampproject/wg-ui-and-a11y for review

2020-09-30 11:33 UTC, adp-developer commented
@alanorozco Friendly ping!

2020-10-02 18:57 UTC, jridgewell commented
/cc @caroqliu Maybe you could take a look?

2021-01-26 02:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ampproject/amphtml?pullRequest=29892) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ampproject/amphtml?pullRequest=29892) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ampproject/amphtml?pullRequest=29892) it.</sub>

2021-02-01 22:43 UTC, caroqliu commented
Hi @adp-developer! Thanks for filing this issue, and sorry it's taken some time to get you a review on the component. All new components should follow the [process for significant changes](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#process-for-significant-changes), including [filing an I2I](https://github.com/ampproject/amphtml/issues/new?assignees=&labels=INTENT+TO+IMPLEMENT&template=intent-to-implement--i2i-.md&title=I2I:%20%3Cyour%20change/update%3E) and [bringing the topic to design review](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md). Once this component has been approved at design review, we'll be sure to review this PR promptly.

2021-04-06 11:39 UTC, adp-developer commented
Hello Caroline,

Thanks for getting back. Could you please let us know if we need to do
something else now?

On Tue, Feb 2, 2021 at 12:43 AM Caroline Liu ***@***.***>
wrote:

> Hi @adp-developer <https://github.com/adp-developer>! Thanks for filing
> this issue, and sorry it's taken some time to get you a review on the
> component. All new components should follow the process for significant
> changes
> <https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#process-for-significant-changes>,
> including filing an I2I
> <https://github.com/ampproject/amphtml/issues/new?assignees=&labels=INTENT+TO+IMPLEMENT&template=intent-to-implement--i2i-.md&title=I2I:%20%3Cyour%20change/update%3E>
> and bringing the topic to design review
> <https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md>.
> Once this component has been approved at design review, we'll be sure to
> review this PR promptly.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ampproject/amphtml/pull/29892#issuecomment-771211319>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AP6YJYEUFXENDOL3UEHAX2DS44VCBANCNFSM4QEV6WEQ>
> .
>

2021-04-06 14:47 UTC, alanorozco commented
@adp-developer Like @caroqliu mentioned:

> All new components should follow the [process for significant changes](https://github.com/ampproject/amphtml/blob/master/contributing/contributing-code.md#process-for-significant-changes), including [filing an I2I](https://github.com/ampproject/amphtml/issues/new?assignees=&labels=INTENT+TO+IMPLEMENT&template=intent-to-implement--i2i-.md&title=I2I:%20%3Cyour%20change/update%3E) and [bringing the topic to design review](https://github.com/ampproject/amphtml/blob/master/contributing/design-reviews.md)

2021-04-20 13:14 UTC, alanorozco requested changes
Reminder that this component is not approved, and its code cannot be reviewed until going to design review.

2021-04-21 15:54 UTC, alanorozco commented
I strongly suggest that work on this is halted.

#33889 needs to go through a design review session first.

2022-01-10 20:49 UTC, Gregable commented
Closing for now. It can be reopened once it has gone through design review.

2022-01-10 20:49 UTC, closed without merging