Update frame.max.html
ampproject/amphtml pull request #30404
Opened 2020-09-25 06:47 UTC by karl1993

2020-09-25 15:19 UTC, powerivq commented
Hey @karl1993 . I don't quite understand the purpose of this PR. Can you explain?

2020-10-01 01:48 UTC, karl1993 commented on 3p/frame.max.html
> -<body style="margin:0">
>

2020-10-01 02:09 UTC, karl1993 reviewed
Fix it

2020-10-01 17:46 UTC, powerivq requested changes
I do not see why we need this here.

2020-10-08 23:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ampproject/amphtml?pullRequest=30404) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ampproject/amphtml?pullRequest=30404) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ampproject/amphtml?pullRequest=30404) it.</sub>

2020-10-09 05:23 UTC, powerivq commented
Closing as inactive.

2020-10-09 05:23 UTC, closed without merging