✅ TestsSlike Video Player - AMP Component
ampproject/amphtml pull request #30416
Opened 2020-09-27 15:33 UTC by SlikeTech

Slike Studio is a TIL's in-house audio-video platform to meet the enterprise needs, which provides live broadcast, on-demand video & podcast solutions. We created this leading Video Platform-as-a-Service, enabling different businesses to create any video solution and workflow, whether standalone or tightly coupled.

This AMP Component is a new component meant for embedding Slike media player, there are certain mandatory parameters as well as customised ones which we can use as per the user configurations required, details of which can be found inside.

2020-09-27 15:52 UTC, SlikeTech commented
@googlebot I consent

2020-09-27 16:49 UTC, SlikeTech commented
@jridgewell
I followed all the processes for ownership and CLA but not able out of it.
Please help.

2020-09-28 16:59 UTC, jridgewell commented
Hi @SlikeTech, don't worry too much about the CLA. You've included multiple commits, with some commits being authored by yourself and some by @ranjan000. As long as both of you comment here that you consent, we can manually verify the CLA has been signed using the associated email addresses in the commit.

For now, I'm sending this to @ampproject/wg-ui-and-a11y for review.

2020-09-28 17:23 UTC, Gregable requested changes
My comments are for the validator changes only.

2020-09-28 17:23 UTC, Gregable commented on extensions/amp-slike/validator-amp-slike.protoascii
> +    requires_usage: EXEMPTED
Remove this line.

2020-09-28 17:23 UTC, Gregable commented on extensions/amp-slike/validator-amp-slike.protoascii
> +    deprecated_allow_duplicates: true
And this line.

2020-09-28 17:23 UTC, Gregable commented on extensions/amp-slike/validator-amp-slike.protoascii
> +   attrs: {
nit. looks like whitespace alignment is off by one here, but I may be reading the diff incorrectly.

2020-09-28 17:23 UTC, Gregable commented on extensions/amp-slike/0.1/test/validator-amp-slike.out
> +PASS
Out file doesn't match the input file. You can regenerate the out file by running from the `validator/` dir

```
python build.py --update_tests
```

2020-09-28 17:23 UTC, Gregable commented on extensions/amp-slike/0.1/test/validator-amp-slike.html
> +<!doctype html>
Needs a copyright comment header and documentation. See similar `.html` test files in other extension directories.

2020-09-29 12:24 UTC, ranjan000 commented
@google I consent.

2020-09-29 12:26 UTC, ranjan000 commented
@google I consent

2020-10-08 23:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ampproject/amphtml?pullRequest=30416) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/ampproject/amphtml?pullRequest=30416) before we can accept your contribution.<br/>**0** out of **3** committers have signed the CLA.<br/><br/>:x: ranjan000<br/>:x: SlikeTech<br/>:x: dhananjay<br/><hr/>**dhananjay** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ampproject/amphtml?pullRequest=30416) it.</sub>

2020-10-09 02:34 UTC, kristoferbaxter commented
After a few mishaps with the iOS GitHub client, I've added Kevin to review.

2020-10-27 07:00 UTC, SlikeTech commented
@google I consent

2020-10-28 15:34 UTC, krdwan commented on extensions/amp-slike/0.1/test/validator-amp-slike.html
> +  Copyright 2015 The AMP HTML Authors. All Rights Reserved.
nit: Copyright 2020

2020-10-28 15:43 UTC, krdwan approved these changes
LGTM

2020-12-28 14:23 UTC, SlikeTech commented
@Gregable All the owners are on board. May I know the owner who is missing?

2020-12-29 05:50 UTC, closed without merging