Fixed amp-list component documentation for Email
ampproject/amphtml pull request #30427
Opened 2020-09-29 05:00 UTC by manisaiprasad

Updated amp-list component documentation for AMP4Email 
Resolves ampproject/amp.dev#4715 issue

📖 Documentation

@CrystalOnScript

2020-09-30 18:31 UTC, CrystalOnScript requested changes
Just a small format nit to make sure it renders correctly on amp.dev. Thanks so much!

2020-09-30 18:31 UTC, CrystalOnScript commented on extensions/amp-list/amp-list.md
>  The URL of the remote endpoint that returns the JSON that will be rendered
```suggestion
### `src` (required)

[filter formats="websites, stories"]

The URL of the remote endpoint that returns the JSON that will be rendered
```

2020-11-04 13:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ampproject/amphtml?pullRequest=30427) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ampproject/amphtml?pullRequest=30427) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ampproject/amphtml?pullRequest=30427) it.</sub>

2021-04-05 18:29 UTC, patrickkettner commented
superceeded by #31588

2021-04-05 18:29 UTC, closed without merging