1% experiment - AdSense/GAM ad request ptt parameter
ampproject/amphtml pull request #30764
Opened 2020-10-20 17:34 UTC by keithwrightbos

For amp-ad type=adsense or doubleclick, 1% experiment that sends new ptt parameter on ad request with fixed value.

2020-10-20 17:49 UTC, jeffkaufman requested changes

2020-10-20 17:49 UTC, jeffkaufman commented on build-system/global-configs/canary-config.json
> +  "doubleclickPttExp": 0.02
adsense-ptt-exp and doubleclick-ptt-exp

2020-10-20 17:49 UTC, jeffkaufman commented on extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
> +          expect(impl.getAdUrl()).to.not.eventually.match(/(\?|&)ptt=12(&|$)/));
Instead of checking for `&ptt=12` we should check for `&ptt=`

2020-10-20 17:49 UTC, jeffkaufman commented on extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
> +      expect(impl.getAdUrl()).to.not.eventually.match(/(\?|&)ptt=13(&|$)/));
same

2020-10-20 17:53 UTC, jeffkaufman approved these changes

2020-10-20 17:53 UTC, jeffkaufman commented on extensions/amp-ad-network-adsense-impl/0.1/test/test-amp-ad-network-adsense-impl.js
> +            /(\?|&)ptt=(&|$)/);
here I do think checking 12 is correct

2020-10-20 17:53 UTC, jeffkaufman commented on extensions/amp-ad-network-doubleclick-impl/0.1/test/test-amp-ad-network-doubleclick-impl.js
> +        /(\?|&)ptt=(&|$)/);
and 13 here

2020-10-20 20:34 UTC, calebcordry approved these changes

2020-10-21 18:38 UTC, lannka approved these changes

2020-10-21 18:39 UTC, merged