add babel-plugin-transform-block-scoping
ampproject/amphtml pull request #30807
Opened 2020-10-21 22:55 UTC by erwinmombay

A discussion in https://github.com/evanw/esbuild/issues/478 has shown that using let and class in same enclosing level has a signigicant performance impact on the Safari browser. To alleviate this problem we transform the let and class constructs into var when it is 'easily' possible.

this should only be turned on for esm/sxg

Co-authored-by: Justin Ridgewell <jridgewell@google.com>
Co-authored-by: erwin mombay <erwinm@google.com>

2020-10-21 23:29 UTC, kristoferbaxter commented
Agree with @jridgewell feedback that we'll need to turn on `mangle` here now (https://github.com/ampproject/amphtml/blob/master/build-system/compile/post-closure-babel.js#L33).

2020-10-21 23:29 UTC, kristoferbaxter requested changes
Mangle will be needed to rename the variable references.

2020-10-21 23:34 UTC, jridgewell approved these changes

2020-10-21 23:45 UTC, kristoferbaxter approved these changes

2020-10-22 00:08 UTC, merged

2020-10-22 01:02 UTC, erwinmombay commented
size before this change:
Computing bundle size for version 2010212121000 at commit 6418ea9.
brotli bundle sizes are:
dist/v0.mjs: 59.49KB

size after this change:
Computing bundle size for version 2010220007000 at commit 9799f73.
brotli bundle sizes are:
dist/v0.mjs: 59.48KB