✨ [amp-autocomplete] Add support for `prefetch` attribute for prefetching remote data
ampproject/amphtml pull request #31021
Opened 2020-11-06 00:53 UTC by dmanek

1. Implemented support for `prefetch` attribute
1. Minor refactoring
1. Added unit test

2020-11-06 17:08 UTC, dmanek commented
cc @caroqliu

2020-11-09 14:11 UTC, caroqliu reviewed
LGTM, however note that users cannot start using this attribute until it is allowed in the [validation rules](https://github.com/ampproject/amphtml/blob/master/extensions/amp-autocomplete/validator-amp-autocomplete.protoascii). Please allow `prefetch` and update the validator tests too. :)

2020-11-10 05:18 UTC, dmanek commented
Thanks for your comments @caroqliu. I've updated the validation rules and added tests, PTAL.

2020-11-10 14:27 UTC, caroqliu approved these changes
Thank you! Looks good. Please also add this attribute to the documentation in `extensions/amp-autocomplete/amp-autocomplete.md`

2020-11-10 16:00 UTC, dmanek commented
Thanks for approving. I've already updated the documentation in `amp-autocomplete.md` 🙂

2020-11-10 16:23 UTC, honeybadgerdontcare requested changes

2020-11-10 16:23 UTC, honeybadgerdontcare commented on extensions/amp-autocomplete/validator-amp-autocomplete.protoascii
> +  attrs: { name: "prefetch" }
please alphabetize by attribute name (e.g. this should go before `query`)

2020-11-10 16:23 UTC, honeybadgerdontcare commented on extensions/amp-autocomplete/validator-amp-autocomplete.protoascii
> +  attrs: { name: "prefetch" }
same here

2020-11-10 16:23 UTC, caroqliu commented
> Thanks for approving. I've already updated the documentation in `amp-autocomplete.md` 🙂

🤦‍♀️  You're right! Ignore me :)

2020-11-10 17:26 UTC, honeybadgerdontcare approved these changes

2020-11-10 22:05 UTC, zhouyx approved these changes

2020-11-10 22:07 UTC, merged