✨ Support enabling Vimeo players do-not-track attribute when using AmpVimeo component
ampproject/amphtml pull request #31406
Opened 2020-12-03 12:51 UTC by frj

Adding an optional 'do-not-track' attribute to AmpVimeo component that causes the dnt=1
attribute to be appended to the vimeo player iframe src url.

This will "prevent the player from tracking session data, including cookies"
for details see: https://developer.vimeo.com/api/oembed/videos

Issue:  #31384

2020-12-03 12:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ampproject/amphtml?pullRequest=31406) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ampproject/amphtml?pullRequest=31406) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ampproject/amphtml?pullRequest=31406) it.</sub>

2020-12-03 17:18 UTC, micajuine-ho reviewed
Hi @frj  Thank you for your contribution. 

Do you we know how this feature will affect video analytics?

2020-12-03 18:20 UTC, oliverlloyd commented
> Do you we know how this feature will affect video analytics?


My understanding is that passing `dnt` will block all tracking, including stats used by https://vimeo.com/analytics

> Setting this parameter to "true" will block the player from tracking any session data, including all cookies and stats. 
>
> (Will have the same effect as enabling a Do Not Track setting in your browser)

https://vimeo.zendesk.com/hc/en-us/articles/360001494447

2020-12-04 09:35 UTC, frj commented
Hi @micajuine-ho, thanks for taking a look. 

As @oliverlloyd says, according to the docs this will block all stats collection.

Ive updated the readme to make this point clearer.

2020-12-04 18:09 UTC, micajuine-ho commented
Sorry just to clarify, dnt=1 will stop the vimeo iframe from tracking session data including cookies. Does this mean that amp-analytics with video triggers will stop working?

2020-12-04 21:24 UTC, oliverlloyd commented
> Does this mean that amp-analytics with video triggers will stop working?

Yes, the `dnt` param _should_ stop the triggers working. The `dnt` contract is that such that all `video-*` triggers should no longer be fired.

However, it looks like `amp-vimeo` doesn't work with `amp-analytics` in any case. Or at least it's not [listed  here](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-video-analytics.md) as a vendor that supports the AMP common video interface.

2020-12-04 21:52 UTC, micajuine-ho commented
Perfect. Thanks for the explanation.

2020-12-04 21:53 UTC, micajuine-ho requested changes

2020-12-04 21:53 UTC, micajuine-ho commented on extensions/amp-vimeo/0.1/test/test-amp-vimeo.js
> +        vimeo.setAttribute('do-not-track', 'do-not-track');
nit: vimeo.setAttribute('do-not-track', '');

2020-12-07 11:00 UTC, frj commented
Hi @micajuine-ho I made the change you suggested. 

The 'percy' test seems to be failing although it look unrelated to this change, ie its also failing on a bunch of other branches.

Let me know if you need anything else.

Thanks again for your help.

2020-12-07 15:13 UTC, micajuine-ho approved these changes

2020-12-07 15:14 UTC, merged