✅ Slike Video Audio Player - AMP Component Introduced
ampproject/amphtml pull request #31855
Opened 2021-01-08 13:32 UTC by SlikeTech

Slike Studio is a TIL's in-house audio-video platform to meet the enterprise needs, which provides live broadcast, on-demand video & podcast solutions. We created this leading Video Platform-as-a-Service, enabling different businesses to create any video solution and workflow, whether standalone or tightly coupled.

This AMP Component is a new component meant for embedding Slike media player, there are certain mandatory parameters as well as customised ones which we can use as per the user configurations required, details of which can be found inside.

Will Yield in better loading time for users as well as the maintaining servers.

2021-01-08 14:06 UTC, SlikeTech commented
@alanorozco Need your help on this **Missing required OWNERS approvals! Suggested**
As per my knowledge I have all the approvals

2021-01-08 18:04 UTC, honeybadgerdontcare commented
@SlikeTech I've added @twifkak for reviewing the validator related files. Note any new files should be copyright 2021. Thanks!

2021-01-09 07:34 UTC, SlikeTech commented
Copyright modified

2021-01-11 21:50 UTC, twifkak requested changes
Sorry for the delay! For validation, this looks pretty close; just a couple changes necessary, I think.

2021-01-11 21:50 UTC, twifkak commented on extensions/amp-slike/validator-amp-slike.protoascii
> +    requires_usage: EXEMPTED
I would recommend ERROR here. EXEMPTED is typically reserved for legacy extensions: https://github.com/ampproject/amphtml/blob/91aaf6f3e28c28117fc6ca0eb660d39161e387ee/validator/validator.proto#L496-L498

Alternatively, it is possible to use NONE, if there is some useful non-nil behavior when the `<script>` is on the page but not the `<amp-slike>`, but from a quick glance at the docs & code that doesn't appear to be the case.

2021-01-11 21:50 UTC, twifkak commented on extensions/amp-slike/0.1/test/validator-amp-slike.out
> +|    <amp-slike layout="responsive" width="150" height="80"></amp-slike>
This does not appear to match the `.html` file. I would expect to see FAIL up top, with the other two invalid amp-slike instances & their error messages here. Try running `gulp validator --update_tests`.

2021-01-11 23:58 UTC, twifkak commented on extensions/amp-slike/validator-amp-slike.protoascii
> +    requires_usage: EXEMPTED
I've since learned you can just delete this line since ERROR is the default value.

2021-01-12 15:43 UTC, SlikeTech commented
@@twifkak changes done.

2021-01-13 05:00 UTC, SlikeTech commented
@twifkak changes done.

2021-01-14 17:14 UTC, SlikeTech commented
@twifkak requires_usage deleted

2021-01-22 20:23 UTC, twifkak commented
Sorry for the delay. The fix to the protoascii looks good to me, thanks!

 `gulp validator --update_tests` still needs to be run (or the changes committed). See the failing test at https://travis-ci.com/github/ampproject/amphtml/jobs/471827545.

2021-04-12 22:25 UTC, Gregable commented
@SlikeTech is this PR still something you are working on?

2021-04-12 22:30 UTC, alanorozco commented
@SilkeTech If you require followup on this PR, please follow the [contribution guidelines](https://github.com/ampproject/amphtml/blob/main/contributing/contributing-code.md). You need to file an Intent-to-Implement issue and it has to be approved during a design review. Please include in your I2I an explanation why you cannot use `amp-video-iframe` instead, [per  the 3rd party video player guidelines](https://github.com/ampproject/amphtml/blob/main/spec/amp-3p-video.md).

2022-01-10 20:54 UTC, Gregable commented
Closing for inactivity.

2022-01-10 20:54 UTC, closed without merging