✨ Fast fetch implementation for Valueimpression network
ampproject/amphtml pull request #32061
Opened 2021-01-20 10:07 UTC by thuyhq

This commit contains a quick fetch implementation for Valueimpression network ads rendering.
This is my first time participating in the AMP Project, looking forward to helping.

2021-01-20 22:02 UTC, jridgewell commented
/to @powerivq

2021-01-22 17:11 UTC, powerivq requested changes

2021-01-25 02:18 UTC, thuyhq commented
Hello @powerivq,
Thank you for your review
I have corrected it according to what you asked.

2021-01-25 11:46 UTC, powerivq commented
@thuyhq Hi, look like it is not building correctly. Could you check the Travis CI detail and fix whatever issues present? thanks.

2021-01-26 04:51 UTC, thuyhq commented
Hi @powerivq,
The errors in Travis CI have been resolved.
What do I need to do next?
Thank you.

2021-01-27 00:02 UTC, powerivq approved these changes

2021-01-27 00:04 UTC, powerivq commented
Adding @estherkim for build-system/compile/bundles.config.extensions.json owner approval
Adding @dvoytenko for the addition of the new extension owner approval.

2021-01-27 16:51 UTC, estherkim approved these changes

2021-01-28 01:26 UTC, dvoytenko approved these changes

2021-02-09 15:30 UTC, thuyhq commented
Hi @powerivq
When is my pull request merged in the main branch?

2021-02-09 16:18 UTC, powerivq commented
@thuyhq could you rebase it on the latest master? Must have all tests passed before merging.

2021-03-03 14:37 UTC, thuyhq commented
Hi @powerivq,
I rebase my branch on master. But then circleCI gives error 
ERROR: Error: Build failed with 1 error:
extensions/amp-instagram/1.0/amp-instagram.js:41:20: error: Could not resolve "../../../build/amp-instagram-1.0.css" 

Looks like this error is not coming from my commit. How do I fix them?
Thanks very much.

2021-03-03 15:01 UTC, powerivq requested changes

2021-03-03 15:01 UTC, powerivq commented on build-system/compile/bundles.config.extensions.json
> +  {"name": "amp-instagram", "version": "1.0", "latestVersion": "0.1"},
See this. You might want to revert this change.

2021-03-03 15:01 UTC, powerivq commented on build-system/compile/bundles.config.extensions.json
> +  {"name": "amp-stream-gallery", "version": "1.0", "latestVersion": "0.1"},
Same here.

2021-03-03 21:06 UTC, powerivq commented
There's a check-lint failure https://app.circleci.com/pipelines/github/ampproject/amphtml/3506/workflows/0c17ee5c-0f3c-4497-bc38-0a2ddce0e5c3/jobs/43154

2021-03-04 17:21 UTC, powerivq approved these changes

2021-03-04 17:21 UTC, merged

2021-03-28 15:18 UTC, thuyhq commented
Hello @powerivq,
When will my pull request be released?

2021-05-07 12:06 UTC, thuyhq commented
Hello @estherkim , @dvoytenko ,
What do I need to do next for my PR to be released?

2021-05-07 21:24 UTC, estherkim commented
Hi @thuyhq, looks like it has been in Stable since Mar 10.