[amp-viewer-integration] Handle redirects case
ampproject/amphtml pull request #32076
Opened 2021-01-20 20:31 UTC by Enriqe

Partial #31838

Handles case where document redirects, resulting in a different origin in the cache URL than what would normally be computed.

Also need to bump up the messaging library version 
https://github.com/ampproject/amphtml/blob/43df70c521b59eec17e62868f7c22fd685ac731e/package.json#L19

2021-01-20 20:36 UTC, jridgewell requested changes

2021-01-20 20:36 UTC, jridgewell commented on extensions/amp-viewer-integration/0.1/messaging/messaging.js
> +            event.origin.endsWith('.cdn.ampproject.org')) &&
Actually, let's change this to check [`cdnProxyRegex`](https://github.com/ampproject/amphtml/blob/e314f8cdc92a0898cbab7ee2483a661cad16cfa9/src/config.js#L74):

```suggestion
            urls.cdnProxyRegex.test(event.origin)) &&
```

2021-01-20 21:57 UTC, jridgewell approved these changes

2021-01-21 20:16 UTC, merged

2021-01-21 20:28 UTC, kristoferbaxter commented
I merged this PR, but a followup is needed where the CDN Regex is not imported.

The reason: this file is not pre-processed before publication, and importers will not necessarily have a file at the specified path.