amp-analytics support SensorsData
ampproject/amphtml pull request #32199
Opened 2021-01-26 11:03 UTC by 869359954

# ♿ amp-analytics support SensorsData

# description
- Sensors Data is a Third party analysis service provider
- we want amp-analytics to support SensorsData

2021-01-26 14:47 UTC, micajuine-ho requested changes

2021-01-26 14:47 UTC, micajuine-ho commented on examples/analytics-vendors.amp.html
> +      <option>sensorsanalytics</option>
Alphabetical order please.

2021-01-26 14:47 UTC, micajuine-ho commented on examples/analytics-vendors.amp.html
> +        },
Place this chunk in alphabetical order with the other vendor chunks.

2021-01-26 14:47 UTC, micajuine-ho commented on examples/analytics-vendors.amp.html
> +
nit: remove newline

2021-01-26 14:47 UTC, micajuine-ho commented on examples/analytics-vendors.amp.html
> +
nit: remove newlines

2021-01-26 14:47 UTC, micajuine-ho commented on extensions/amp-analytics/0.1/vendors/sensorsanalytics.json
> +
remove newline

2021-01-27 07:48 UTC, 869359954 commented
@micajuine-ho  I have fixed the previous problem, please help help help me review

2021-01-27 15:13 UTC, micajuine-ho requested changes
You need to add tests to `extensions/amp-analytics/0.1/test/vendor-requests.json` based off of `extensions/amp-analytics/0.1/vendors/sensorsanalytics.json`.

2021-01-28 03:37 UTC, 869359954 commented
@micajuine-ho  I got it !  I have added . Please help help help me review  ,thank you

2021-01-28 15:04 UTC, micajuine-ho approved these changes

2021-01-28 15:05 UTC, merged