♻️ Move RTC to a service
ampproject/amphtml pull request #32386
Opened 2021-02-03 09:53 UTC by powerivq

https://github.com/ampproject/amphtml/pull/31101

It moves the rtc related code into a service.

2021-02-04 18:14 UTC, calebcordry requested changes

2021-02-04 18:14 UTC, calebcordry commented on extensions/amp-a4a/0.1/amp-a4a.js
> +              realTimeConfig.maybeExecuteRealTimeConfig(
it seems like this can be `undefined`?  ie cannot read property maybeExec of undefined...

2021-02-04 19:03 UTC, calebcordry approved these changes

2021-02-04 19:03 UTC, calebcordry commented on extensions/amp-a4a/0.1/amp-a4a.js
> +              realTimeConfig.maybeExecuteRealTimeConfig(
never mind, indentation confused me :)

2021-02-05 19:19 UTC, powerivq commented
Adding @jridgewell for src/service owner approval.

2021-02-05 19:24 UTC, jridgewell approved these changes
Owners approval

2021-02-05 22:47 UTC, merged