Remove sync measurement from ad iframes: experiment
ampproject/amphtml pull request #32437
Opened 2021-02-04 19:25 UTC by samouri

Followup to: https://github.com/ampproject/amphtml/pull/31753
cc @calebcordry.

2021-02-04 20:15 UTC, calebcordry commented
cc/ @zombifier incoming client side experiment

2021-02-04 20:21 UTC, calebcordry requested changes
where is the `experiments/ads-initial-intersection-exp` file? :)

2021-02-04 20:32 UTC, calebcordry approved these changes

2021-02-05 00:45 UTC, dvoytenko approved these changes

2021-02-10 23:12 UTC, merged