♻️ Build all existing 3p vendors integrations file
ampproject/amphtml pull request #32675
Opened 2021-02-16 14:09 UTC by powerivq

Add all existing 3p vendors.

2021-02-16 17:20 UTC, calebcordry requested changes
Looks like the export name might be wrong for weborama?

2021-02-16 17:35 UTC, powerivq commented
> Looks like the export name might be wrong for weborama?

https://github.com/ampproject/amphtml/blob/3027b8e0c2a35f4fffac2f9a56274c0215758c76/3p/integration.js#L558 its vendor type name is weborama-display.

2021-02-16 17:38 UTC, calebcordry commented on 3p/vendors/weborama-display.js
> +import {weborama} from '../../ads/vendors/weborama';
This is the line breaking on travis.

2021-02-16 17:40 UTC, powerivq commented
OO yeah you're right.

2021-02-16 18:54 UTC, calebcordry approved these changes

2021-02-17 17:11 UTC, lannka approved these changes

2021-02-18 07:57 UTC, powerivq commented
@rsimha Needs your owner approval on `build-system/tasks/dist.js` change. It prevents building 3p vendors when `core_runtime_only` is set.

2021-02-19 19:47 UTC, danielrozenberg approved these changes
Approval for build-system change

2021-02-19 20:07 UTC, merged

2021-02-20 00:18 UTC, rsimha commented
@powerivq @calebcordry @lannka This PR has increased the duration of `gulp dist` by a factor of 2.5x (~4m -> ~10m).

Since this affects our local development, CI, and release workflows, can we revert until there's a discussion about the purpose of this change? There may be other ways build 3p vendor files without affecting the build time for the runtime.