✨ Add Highfivve as AMP RTC vendor
ampproject/amphtml pull request #33203
Opened 2021-03-11 15:34 UTC by muuki88

This pull requests adds AMP RTC vendor [Highfivve](https://highfivve.com) to the list of AMP RTC vendors.

### Example integration

```html
<amp-ad
  width="320"
  height="50"
  type="network-foo"
  data-slot="/1234/5678"
  rtc-config='{
    "vendors": {
      "highfivve": {"TAG_ID": "1", "ACCOUNT_ID":"my-account"}
      },
    "timeoutMillis": 750}'
>
</amp-ad>
```

2021-03-11 15:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ampproject/amphtml?pullRequest=33203) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ampproject/amphtml?pullRequest=33203) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ampproject/amphtml?pullRequest=33203) it.</sub>

2021-03-12 18:10 UTC, calebcordry requested changes
Thanks for contributing! Can you please remove any changes to the `package-lock.json` file.

2021-03-12 18:12 UTC, JoeSephh approved these changes

2021-03-12 20:19 UTC, muuki88 commented
For sure 😅 I didn't realized the changes.

2021-03-15 08:25 UTC, muuki88 commented
Oh boy... I messed that one up... Should I close and open a new PR :grimacing:

2021-03-15 08:53 UTC, closed without merging