performance-impl: exclusively use ampdoc visibility state
ampproject/amphtml pull request #33310
Opened 2021-03-16 23:43 UTC by samouri

2021-03-17 14:43 UTC, rcebulko approved these changes
I support any chance to clean up unneeded code! Though I, like you, have no idea why it's written like this in the first place. /cc @rsimha to double-check testing changes for known gotchas

2021-03-17 16:50 UTC, rsimha reviewed
These changes generally LGTM, but I think we should resurrect our performance tests to better test things. Would it be possible to uncomment these lines in a test PR and see how the performance tests do?

https://github.com/ampproject/amphtml/blob/db781bd6c2dc300ab91f9e8ef5ce500768165ee4/.circleci/config.yml#L335-L339

**Notes:**
- You'll need to replace `push_builds_only` with `push_and_pr_builds` to get the tests to run during the PR check.
- The reason we stopped running these tests is that they were unreliable, and took ~30 minutes for each run, which slowed down CI for everyone. (See https://github.com/ampproject/amphtml/issues/12128#issuecomment-697634617)
- If these tests can be made to run reliably in < 10 mins, we'll have have more confidence in the changes in this PR, and in other PRs that could affect performance.

2021-04-05 23:03 UTC, erwinmombay requested changes
per @jridgewell "Something is wrong if this requires a bundle size update"

2021-04-05 23:04 UTC, erwinmombay commented
LOL ignore my comment, wrong pull request. too many tabs 💀

2021-04-06 02:14 UTC, jridgewell approved these changes

2021-04-15 14:21 UTC, merged

2021-04-15 14:21 UTC, samouri commented
```
dist/amp4ads-v0.js: Δ -0.05KB
dist/amp4ads-v0.mjs: Δ -0.02KB
dist/v0.js: Δ -0.10KB
dist/v0.mjs: Δ -0.02KB
```