Brid player support for carousel
ampproject/amphtml pull request #33475
Opened 2021-03-25 10:56 UTC by grajzer

2021-03-25 14:18 UTC, alanorozco reviewed
Would you mind adding a test for the required attribute error? There's a couple of similar tests:

https://github.com/ampproject/amphtml/blob/1e15159d609ecf1f9584191612e0f3e1d4a41bcc/extensions/amp-brid-player/0.1/test/test-amp-brid-player.js#L103-L112

2021-03-25 16:14 UTC, honeybadgerdontcare approved these changes
approved for validation after alphabetical change and adding a test per alan

2021-03-25 16:14 UTC, honeybadgerdontcare commented on extensions/amp-brid-player/validator-amp-brid-player.protoascii
> +    name: "data-carousel"
please list in alphabetical order by attribute name.

2021-03-25 18:54 UTC, alanorozco requested changes
Requesting changes for test mentioned above.

2021-03-26 10:06 UTC, grajzer commented
Thank you @alanorozco @honeybadgerdontcare , these changes are implemented.

2021-03-31 17:49 UTC, alanorozco approved these changes

2021-03-31 17:50 UTC, merged