✨ [Story video] Google cache validation
ampproject/amphtml pull request #33611
Opened 2021-04-02 16:09 UTC by mszylkowski

Added the `enable-google-video-cache` attribute to amp-videos inside amp-story, which requires the extension `amp-url-cache`

2021-04-02 17:20 UTC, newmuis requested changes
Sorry, can we please reach alignment on the comments in https://docs.google.com/document/d/1Ti1JdC8JxXXIKTq6gh5_0N6Odm5WWXgy5vQ-mC7U7dE before proceeding?

2021-04-02 17:22 UTC, mszylkowski commented
Yes, I'm reverting the changes unrelated to the validation, and this will stay as draft until we resolve the diffbase PR

2021-04-21 20:50 UTC, gmajoulet approved these changes

2021-04-21 20:50 UTC, gmajoulet commented on extensions/amp-video/0.1/test/validator-amp-video-google-cache-story.out
> +|    Tests for amp-video tag under the google cache.
Plz remove google in these files/filenames

2021-04-21 21:07 UTC, newmuis approved these changes

2021-04-22 14:41 UTC, gmajoulet commented
to @ampproject/wg-caching for approval

2021-04-22 18:18 UTC, MichaelRybak approved these changes

2021-04-22 19:15 UTC, merged

2021-06-01 18:59 UTC, westonruter commented on extensions/amp-cache-url/validator-amp-cache-url.protoascii
> +    version: "0.1"
Is there a reason why `latest` was omitted here? See #34636.