🐛 [amp-story] don't send story-page-visible for ad pages
ampproject/amphtml pull request #33884
Opened 2021-04-17 00:01 UTC by calebcordry

Closes #33783

2021-04-19 14:58 UTC, processprocess approved these changes
Looks good based on the discussion in #33783.
I'll default to @Enriqe for final approval.

2021-04-19 15:41 UTC, Enriqe requested changes
Thanks for the PR with tests :) just a couple of comments

2021-04-19 15:41 UTC, Enriqe commented on extensions/amp-story/1.0/test/test-story-analytics.js
> +    expect(triggerAnalyticsStub).calledOnceWithExactly(
```suggestion
    expect(triggerAnalyticsStub).to.have.been.calledOnceWithExactly(
```

2021-04-19 15:41 UTC, Enriqe commented on extensions/amp-story/1.0/story-analytics.js
> +        if (!pageId || this.storeService_.get(StateProperty.AD_STATE)) {
```suggestion
        const isAd = this.storeService_.get(StateProperty.AD_STATE); 
        if (!pageId || isAd) {
```

2021-04-19 16:02 UTC, gmajoulet approved these changes

2021-04-19 23:38 UTC, calebcordry commented on extensions/amp-story/1.0/test/test-story-analytics.js
> +  it('does not send story-page-visible on ad page', () => {
new test added.

2021-04-20 12:06 UTC, Enriqe approved these changes
🎉

2021-04-23 19:55 UTC, calebcordry commented
Merging this one is blocked by #33993

2021-04-23 23:50 UTC, merged