Add rcmwidget ads extension
ampproject/amphtml pull request #33888
Opened 2021-04-19 10:12 UTC by yulya9060

Add rcmwidget ads extension

2021-04-19 10:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ampproject/amphtml?pullRequest=33888) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ampproject/amphtml?pullRequest=33888) before we can accept your contribution.<br/><hr/>**y.saltrukovich** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ampproject/amphtml?pullRequest=33888) it.</sub>

2021-04-23 15:10 UTC, powerivq requested changes
LGTM except these comments

2021-04-23 15:10 UTC, powerivq commented on ads/vendors/rcmwidget.js
> + * Copyright 2020 The AMP HTML Authors. All Rights Reserved.
2021

2021-04-23 15:10 UTC, powerivq commented on ads/vendors/rcmwidget.md
> +Copyright 2017 The AMP HTML Authors. All Rights Reserved.
2021

2021-04-23 15:11 UTC, powerivq requested changes

2021-04-23 15:11 UTC, powerivq commented on ads/vendors/rcmwidget.js
> +  validateData(data, [
Nit: https://app.circleci.com/pipelines/github/ampproject/amphtml/7472/workflows/5d1a639a-0245-4fc2-bd30-b909bd55be58/jobs/109883

2021-04-23 15:25 UTC, yulya9060 commented on 3p/integration-lib.js
> +  'rcmwidget',
remove

2021-04-23 15:25 UTC, yulya9060 commented on ads/vendors/rcmwidget.js
> + * Copyright 2020 The AMP HTML Authors. All Rights Reserved.
fix

2021-04-23 15:25 UTC, yulya9060 commented on ads/vendors/rcmwidget.md
> +Copyright 2017 The AMP HTML Authors. All Rights Reserved.
fix

2021-04-23 15:35 UTC, yulya9060 commented on ads/vendors/rcmwidget.js
> +  validateData(data, [
fix again)

2021-04-23 19:24 UTC, powerivq approved these changes

2021-04-26 17:48 UTC, powerivq commented
@yulya9060 Could you rebase your branch against the latest main branch? It looks like something missing is preventing your PR from being tested.

2021-04-27 08:28 UTC, yulya9060 commented
> @yulya9060 Could you rebase your branch against the latest main branch? It looks like something missing is preventing your PR from being tested.

done

2021-04-27 16:32 UTC, merged