✨ Extend preventDefault() from keypress to click
ampproject/amphtml pull request #33892
Opened 2021-04-19 16:58 UTC by pewgeuges

Resolves #33625 one way.

/cc @westonruter @milindmore22

If preventing the default action is a good feature on keypress, this PR suggests implementing it for click events too.

Note: This is a desperate attempt to pay back to AMP-WP off WP since implementing AMP compat into the intended product is compromised (▲Please don’t link that issue).

2021-04-30 15:31 UTC, erwinmombay commented
@caroqliu im not too familiar with this code base, would you mind triaging or reviewing with me?

2021-04-30 19:54 UTC, caroqliu requested changes

2021-04-30 20:25 UTC, pewgeuges commented on src/service/action-impl.js
> +          }
> Are there concrete examples of what kind of interactions this would affect?

It caused https://github.com/ampproject/amphtml/issues/33625

2021-05-02 18:36 UTC, pewgeuges commented
https://github.com/ampproject/amphtml/pull/33893#issuecomment-830851834 applies also to this PR, that might then be preferrable over its twin.

2022-10-01 10:05 UTC, closed without merging