✨ Digiteka amp-ad => Add new param
ampproject/amphtml pull request #33909
Opened 2021-04-20 11:59 UTC by marcDigiteka

Add the option of passing thru a url encoded, json encoded array of values

2021-04-20 16:37 UTC, powerivq requested changes

2021-04-20 16:37 UTC, powerivq commented on 3p/integration.js
> +register('digiteka', digiteka);
Nit: order it alphabetically

2021-04-20 16:38 UTC, powerivq commented
Also needs to fix the conflict and create a new file under 3p/vendors/digiteka.js

2021-04-21 06:50 UTC, marcDigiteka commented on 3p/integration.js
> +register('digiteka', digiteka);
Done.. :)

2021-04-21 07:06 UTC, powerivq approved these changes

2021-04-21 07:15 UTC, merged