🐛 [amp-next-page 1.0] Forward viewer CID capabilities to shadowdoc children
ampproject/amphtml pull request #33956
Opened 2021-04-22 16:12 UTC by micajuine-ho

Closes #32305

2021-04-22 17:47 UTC, micajuine-ho commented
/cc @jridgewell Do you think there's anything wrong with forwarding the host page's ampdoc's capabilities exposed by the Viewer to the children shadowdoc's ampdocs?

2021-04-22 23:02 UTC, dmanek approved these changes

2021-04-24 00:19 UTC, jridgewell requested changes
Can multidoc handle all of the [capabilities](https://github.com/ampproject/amphtml/blob/main/extensions/amp-viewer-integration/CAPABILITIES.md)?

2021-04-26 13:12 UTC, micajuine-ho commented
@jridgewell Thanks for linking the documentation. I would be hesitant to assume that multidoc can handle all of the capabilities. So, I think we should only pass in CID capabilities if it is there.

2021-04-26 18:57 UTC, jridgewell commented on extensions/amp-next-page/1.0/service.js
> +    }
Please use `viewer.hasCapibility`

2021-04-26 19:11 UTC, jridgewell approved these changes

2021-04-27 13:05 UTC, merged