amp-ad type=tagon
ampproject/amphtml pull request #34730
Opened 2021-06-07 12:41 UTC by Naxulanth

Provides support for amp-ad type=tagon

2021-06-07 12:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ampproject/amphtml?pullRequest=34730) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ampproject/amphtml?pullRequest=34730) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ampproject/amphtml?pullRequest=34730) it.</sub>

2021-06-07 18:08 UTC, powerivq requested changes

2021-06-07 18:08 UTC, powerivq commented on ads/vendors/tagon.js
> + * Copyright 2016 The AMP HTML Authors. All Rights Reserved.
Nit: 2021

2021-06-07 18:08 UTC, powerivq commented on ads/vendors/tagon.md
> +Copyright 2016 The AMP HTML Authors. All Rights Reserved.
Nit: 2021

2021-06-07 23:08 UTC, powerivq commented
Please fix all the conflicts.

2021-06-08 03:45 UTC, powerivq approved these changes

2021-06-08 06:36 UTC, powerivq commented
Please fix the error https://app.circleci.com/pipelines/github/ampproject/amphtml/10780/workflows/fc8ea9ee-7191-4491-9d73-76f62fcafd93/jobs/169252

2021-06-09 06:02 UTC, powerivq commented
Tips: You can run `amp lint --fix` to fix the problems.

2021-06-15 07:52 UTC, powerivq commented
Needs to resolve the merge conflict, or the tests won't run.

2021-06-18 18:11 UTC, powerivq commented
Hey you will need to adopt the new patterns to have the new JS style error fixed. Sorry for the problems you are facing.

2021-06-28 09:57 UTC, Naxulanth commented
Hey,

Is the build failing due to a problem on my side?

2021-06-28 19:05 UTC, merged