✨  Add Wunderkind ads extension
ampproject/amphtml pull request #34873
Opened 2021-06-15 17:15 UTC by weirdian2k3

This PR provides support for <amp-ad type="wunderkind" />

Closes #34871

2021-06-26 13:32 UTC, weirdian2k3 commented
hi @lannka , do you think you'll be able to take a look at this this week? I have a follow-up PR to file once this is merged

2021-07-09 00:02 UTC, weirdian2k3 commented
@calebcordry Hi Caleb! This is the PR I mentioned

2021-07-09 00:02 UTC, calebcordry requested changes
Just a couple nits

2021-07-09 00:02 UTC, calebcordry commented on ads/vendors/wunderkind.js
> + * Copyright 2016 The AMP HTML Authors. All Rights Reserved.
nit: 2020

2021-07-09 00:02 UTC, calebcordry commented on ads/vendors/wunderkind.md
> +Copyright 2016 The AMP HTML Authors. All Rights Reserved.
nit:2020

2021-07-09 00:10 UTC, calebcordry approved these changes

2021-07-09 13:46 UTC, weirdian2k3 commented
Hi @calebcordry !

Would you be able to see what is causing these failures?

2021-07-09 18:56 UTC, calebcordry commented
@weirdian2k3 this appears to be some unrelated babel error. Can you try syncing to latest master? Let me know if you have issues, thanks.

2021-07-10 12:27 UTC, weirdian2k3 commented
@calebcordry updated to master, thank you!

2021-07-12 19:21 UTC, weirdian2k3 commented
@calebcordry if you get a moment, could you approve the workflow so that I can see if the update fixed it?

2021-07-12 19:46 UTC, calebcordry commented on 3p/vendors/wunderkind.js
> +import {draw3p, init} from '../integration-lib';
ah I think these were updated while you were working on this PR. Looks like they are now `#3p/integration-lib`, `#3p/3p`, and `#ads/vendors/wunderkind`

2021-07-12 20:00 UTC, weirdian2k3 commented
@calebcordry thank you for catching that! I've updated the file, which disabled auto-merge

2021-07-12 23:33 UTC, calebcordry commented
looks like now we have some formatting errors :( you can expose them by running `amp prettify` or following the ciricleci link above.

2021-07-13 12:45 UTC, weirdian2k3 commented
@calebcordry 14th times the charm, I've updated the formatting

2021-07-13 18:19 UTC, merged

2021-07-13 18:19 UTC, calebcordry commented
🎉 Thanks for contributing!