✨ [amp-render] validation changes for layout="container"
ampproject/amphtml pull request #34964
Opened 2021-06-22 18:06 UTC by dmanek

2021-06-22 20:07 UTC, honeybadgerdontcare requested changes
Do we know why container was invalid to start for `amp-render` and why it should be changed now?

2021-06-22 20:13 UTC, dmanek commented
My apologies, should have provided more context to begin with. The initial roll out of amp-render did not support container layout support. We're adding it now as a fast follow.

2021-06-22 20:18 UTC, honeybadgerdontcare approved these changes
thank you for the quick reply, approving but expecting @antiphoton to do the true approval for validation.

2021-06-23 17:52 UTC, antiphoton approved these changes

2021-06-23 18:12 UTC, merged