🐛 [amp-render] add missing validation rule for `template` attribute
ampproject/amphtml pull request #35011
Opened 2021-06-23 23:05 UTC by dmanek

Fixes #35004

2021-06-23 23:12 UTC, honeybadgerdontcare requested changes

2021-06-23 23:12 UTC, honeybadgerdontcare commented on extensions/amp-render/validator-amp-render.protoascii
> +    value: "never" # alternative to "no" introduced in amp-render
could you reference the PR here?

2021-06-23 23:12 UTC, honeybadgerdontcare commented on extensions/amp-render/1.0/test/validator-amp-render.out
> +|      <template id="found"></template>
add comment regarding this test failure

2021-06-23 23:44 UTC, dmanek commented
Thanks for the instant code review 🙂

2021-06-24 00:06 UTC, honeybadgerdontcare approved these changes

2021-06-24 03:50 UTC, merged