dep-check: change to use sync methods
ampproject/amphtml pull request #35537
Opened 2021-08-05 09:54 UTC by powerivq

Did not notice comments on https://github.com/ampproject/amphtml/pull/35367

This PR addresses it.

2021-08-05 17:04 UTC, danielrozenberg requested changes

2021-08-05 17:04 UTC, danielrozenberg commented on build-system/tasks/dep-check.js
> +  const extensions = fs.promises.readdirSync('extensions');
```suggestion
  const extensions = fs.readdirSync('extensions');
```

2021-08-05 17:04 UTC, danielrozenberg commented on build-system/tasks/dep-check.js
> +  const vendors = fs.promises.readdirSync('3p/vendors');
```suggestion
  const vendors = fs.readdirSync('3p/vendors');
```

2021-08-19 15:09 UTC, samouri requested changes
I actually think this is less desirable than the async version (https://github.com/ampproject/amphtml/pull/35367#discussion_r692203170)

> My impression was that the await version was always preferred otherwise you block any other action that could happen concurrently. For example processing multiple getEntryPointModules concurrently would be sped up by using the async vs sync call

2021-08-23 19:14 UTC, powerivq commented
@samouri Make sense. Closing this PR.

2021-08-23 19:14 UTC, closed without merging