Remove getIntersectionChangeElementLayoutBox from amp-iframe.
ampproject/amphtml pull request #35860
Opened 2021-08-30 13:57 UTC by samouri

2021-08-30 18:18 UTC, jridgewell requested changes
Let's get an approval from Ads team.

2021-08-31 01:13 UTC, samouri commented
@ampproject/wg-monetization

2021-08-31 01:36 UTC, powerivq approved these changes
Do not think this is going to affect ads. LGTM

2021-08-31 02:51 UTC, jridgewell approved these changes

2021-08-31 15:21 UTC, merged

2021-08-31 15:21 UTC, samouri commented
```
dist/v0/amp-iframe-0.1.mjs: Δ -0.16KB
dist/v0/amp-iframe-0.1.js: Δ -0.15KB
```