R9x ad vendor
ampproject/amphtml pull request #37288
Opened 2022-01-03 13:36 UTC by vishalvanpariya

2022-01-04 15:23 UTC, kristoferbaxter requested changes
Looks like a formatting error was detected by CI. Can you address @vishalvanpariya?

```
checks.js Running amp lint --local_changes...
[13:39:02] Using task file project/amp.js
[13:39:02] Starting 'lint'...
[13:39:04] 
ads/ads.extern.js
  619:1  error  Delete `⏎`  prettier/prettier

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
  ```

2022-01-18 15:03 UTC, vishalvanpariya commented
Hi @kristoferbaxter, errors are fixed now.

2022-01-25 12:13 UTC, vishalvanpariya commented
@kristoferbaxter any update on this?

2022-06-10 02:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ampproject/amphtml?pullRequest=37288) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/ampproject/amphtml?pullRequest=37288) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: vishalvanpariya<br/>:x: VishalTLGC<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ampproject/amphtml?pullRequest=37288) it.</sub>

2022-08-10 17:11 UTC, vishalvanpariya commented
@kristoferbaxter please merger PR.

2023-08-04 21:35 UTC, powerivq requested changes

2023-08-04 21:35 UTC, powerivq commented on ads/vendors/andbeyond.md
> +    data-siteid="9999"
That is another vendor's document. Can you add yours instead?

2023-08-04 21:36 UTC, powerivq commented
We are sweeping through PRs and found this. If you are still interested, please sign the CLA and fix the errors. @vishalvanpariya

2024-09-06 11:55 UTC, closed without merging