🐛  🏗  Fix `amp lint` being run outside of CI
ampproject/amphtml pull request #37348
Opened 2022-01-11 23:34 UTC by rileyajones

I'm not sure when this began but `amp lint` is currently not passing outside of CI due to a handful of old restricted imports.

2022-01-11 23:44 UTC, jridgewell approved these changes

2022-01-12 17:13 UTC, rsimha reviewed
Are you seeing errors or warnings? IIRC, @rcebulko made it so that a subset of warnings are silenced during CI but show up during development so that they can be gradually fixed as code is changed.

**Edit:** Relevant thread: https://github.com/ampproject/amphtml/pull/33016#discussion_r586931446

2022-01-12 17:14 UTC, rcebulko reviewed
What do you mean not passing? As in giving a warning or throwing an error?

2022-01-12 17:16 UTC, rcebulko requested changes
I think this is the result of a different file being removed, since `fetch.js` polyfill was exempted previously. I'm actively looking into this, could you wait a few while I investigate?

2022-01-12 17:20 UTC, rcebulko commented on src/.eslintrc.js
> +            'except': ['./core', './polyfills', './utils/log'],
This file prevents us from accidentally pulling in large subsystems, ex. importing the entire logging system by mistake in certain areas of code that shouldn't, such as code that may be bundled with Bento components where we don't want all the bytes of a logging system we shouldn't use. Individual files with "illegal" imports, like `#polyfills/fetch` which depends on `#utils/log`, are excluded in the `overrides` section below. They don't do anything in CI, but they give a warning locally. This is WAI, and a fresh `main` checkout and `amp lint` run seems to indicate that all is as it should be and there are no new errors.

2022-01-12 18:12 UTC, rileyajones commented
@rcebulko I'm happy to wait your investigation, thanks for looking into this

2022-01-12 18:51 UTC, rcebulko commented
> @rcebulko I'm happy to wait your investigation, thanks for looking into this

AFAICT this is working as intended, and `amp lint` doesn't fail, it logs warnings. Are you experiencing something different?

2022-01-12 19:32 UTC, rileyajones commented
After an offline discussion with @rcebulko it seems that the root problem behind this is being phased out.

2022-01-12 19:32 UTC, closed without merging