♻️ 🏗 Move all remaining Bento component to the `src/bento` directory
ampproject/amphtml pull request #37573
Opened 2022-02-04 00:16 UTC by rileyajones

I've been working on moving Bento components to `src/bento` in groups of common functionality. However, I've now run out of sizable logical groupings leading to this collection of uncategorizable components.

#36461

2022-02-08 20:07 UTC, alanorozco requested changes
We have to address these blocking action items first:

- https://github.com/ampproject/bentojs.dev/pull/175 should be merged
- `write-package-files.js` should reference `src/bento/components` instead of `extensions/`

2022-03-03 18:44 UTC, rileyajones commented
> We have to address these blocking action items first:
> 
> * [ampproject/bentojs.dev#175](https://github.com/ampproject/bentojs.dev/pull/175) should be merged. If not, undo duplicate `README.md` and `example/` paths and move them later.
> * `write-package-files.js` should reference `src/bento/components` instead of `extensions/`
https://github.com/ampproject/bentojs.dev/pull/175 is now merged
#37766 handles updating the publishing flow in `write-package-files.js`
@alanorozco would you mind taking another look?

2022-03-04 17:39 UTC, dmanek commented
Curious as to why the `js` files have been copied over, but the `README.md` are new files even though https://github.com/ampproject/bentojs.dev/pull/175 is now merged?

2022-04-07 20:14 UTC, dethstrobe approved these changes

2022-08-10 19:36 UTC, closed without merging