♿ [amp story page attachment] Prevent header close button from being tabbable when closed
ampproject/amphtml pull request #37707
Opened 2022-02-16 16:41 UTC by processprocess

The close button is currently tabbable, causing the page to shift.
<img width="352" alt="Screen Shot 2022-02-16 at 10 30 20 AM" src="https://user-images.githubusercontent.com/3860311/154311260-174b8667-aeab-4256-9ceb-2d58fd7fe52f.png">

This PR sets a tabindex on the button to hide the element. 
Even though aria-hidden is on the parent, it does not hide interactive children from keyboard tabbing.

[From web.dev](https://web.dev/aria-hidden-focus/):
> If the hidden element contains a focusable element, assistive technologies won't read the focusable element, but keyboard users will still be able to navigate to it, which can cause confusion.

2022-02-17 03:14 UTC, calebcordry requested changes
Can we also add a unit test?

2022-02-17 03:14 UTC, calebcordry commented on extensions/amp-story-page-attachment/0.1/amp-story-page-attachment.js
> +    this.toggleCloseButtonTabIndex_(false);
Should this be `true`?

2022-02-17 17:05 UTC, calebcordry approved these changes

2022-02-18 21:06 UTC, gmajoulet approved these changes
🏅

2022-02-18 22:29 UTC, merged