✨ Add UACH signals to amp-ad-exit.
ampproject/amphtml pull request #37868
Opened 2022-03-14 18:01 UTC by zombifier

Since these signals are asynchronous and amp-ad-exit only allows sync signals, a sync version that requires the async version to be called is added. This means this should only be used in conjunction with components that also use URL substitution like amp-analytics.

2022-03-14 18:02 UTC, zombifier commented
cc @powerivq @calebcordry

2022-03-15 18:11 UTC, powerivq commented
@erwinmombay for url-replacement owner approval

2022-03-16 04:02 UTC, powerivq requested changes

2022-03-16 04:02 UTC, powerivq commented on src/service/url-replacements-impl.js
> +    if (this.cachedUach_[variable]) {
I think checking `if (variable in this.cachedUach_)` would make more sense. Otherwise a `false` value in the dict would fail this check.

2022-03-16 22:57 UTC, powerivq approved these changes

2022-03-23 16:11 UTC, erwinmombay approved these changes

2022-03-23 16:11 UTC, erwinmombay commented
@powerivq sorry for delay. approved

2022-03-23 16:22 UTC, erwinmombay commented on src/service/url-replacements-impl.js
> +      (variable) => this.cachedUach_[variable],
is the "empty" return type consistent between async and sync? i see a `Promise.resolve('')` as a default return on the async side so i was wondering if the sync side will also always return empty string or can it be sometimes `undefined`? and if it is undefined are there side effect to that?

2022-03-24 20:51 UTC, powerivq approved these changes

2022-03-24 20:59 UTC, zombifier commented
Hmm got the bundle size warning only after the nullish coalescing change. I know it's polyfilled but that still sounds strange to me. I'll try reverting it and see what happens.

2022-03-24 22:03 UTC, powerivq commented
@zombifier I think it is flaky. I would just ask someone to approve

2022-03-24 22:56 UTC, powerivq commented
@erwinmombay Re-requesting for the bundle size approval. Feel this change is minimal and probably is caused by brotli instability.

2022-03-29 18:04 UTC, erwinmombay approved these changes

2022-03-29 18:04 UTC, merged