Upgrade to mustache 4.2.2 for Bento components
ampproject/amphtml pull request #37944
Opened 2022-03-23 16:49 UTC by dmanek

1. disable import from third_party/mustache
2. upgrade mustache.js to 4.2.2

2022-03-25 16:58 UTC, jridgewell requested changes
A copy paste like this breaks copyright license:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. – MIT License

We must move this file into the `third_party` directory, and add a `LICENSE` file in the same directory.

2022-03-25 18:30 UTC, dmanek commented
@jridgewell ah thanks! Is it ok to create it a `src/bento/third_party` since that I believe the entirety of `src/bento' is going to migrated into a new repo?

2022-03-25 19:29 UTC, jridgewell commented
Sure

2022-03-28 16:14 UTC, jridgewell approved these changes

2022-03-29 21:47 UTC, merged