🐛 amp-story-shopping Fixes remote shopping data loading on refresh with page attachment open
ampproject/amphtml pull request #38041
Opened 2022-04-07 21:45 UTC by jshamble

2022-04-08 15:11 UTC, processprocess requested changes
The conditionals are getting hard to follow and are spanning across 2 functions.
This makes the code difficult to read and will make maintenance more difficult.

To follow the call stack, it looks like `onAttachmentStateUpdate_` is  called on refresh before data is loaded, causing [Object.values here](https://github.com/ampproject/amphtml/blob/main/extensions/amp-story-shopping/0.1/amp-story-shopping-attachment.js#L198) to throw the error.

Is there a different approach that reduces conditionals?

2022-04-08 15:11 UTC, processprocess commented on extensions/amp-story-shopping/0.1/amp-story-shopping-attachment.js
> +    }
Without checking if we're on the active page first, code will run on all pages with this component.

2022-04-08 15:11 UTC, processprocess commented on extensions/amp-story-shopping/0.1/amp-story-shopping-attachment.js
> +      // or when the shopping attachment is opened when product data is loaded.
```suggestion
      // or when page attachment state is open on refresh.
```

2022-04-11 19:45 UTC, jshamble commented
@processprocess couldn't think of a different approach that reduces the conditionals after trying a few combinations.

2022-04-12 17:37 UTC, processprocess commented
Check out the approach in #38090 and how it uses `Promise.reject` to prevent `layoutCallback` from running.
This way can remove conditionals and log why the component isn't rendering.
The approach could also fix #38035

2022-04-12 21:00 UTC, gmajoulet commented
Could you link me to the code that reopens the shopping attachment on page reload?
I'm curious as to why you need to move these checks, the `activeProductData` should be restored from the history entry, and everything should work properly

2022-04-12 21:51 UTC, jshamble commented
@gmajoulet 
Shopping attachment updates happen in the following two functions here via the store service
```
onAttachmentStateUpdate_
onShoppingDataUpdate_
```

Specifically when `updateTemplate_` is called.

```
   this.storeService_.subscribe(
      StateProperty.PAGE_ATTACHMENT_STATE,
      (isOpen) => this.onAttachmentStateUpdate_(isOpen),
      true /** callToInitialize */
    );
    this.storeService_.subscribe(
      StateProperty.SHOPPING_DATA,
      (shoppingData) => this.onShoppingDataUpdate_(shoppingData),
      true /** callToInitialize */
    );
```

The issue is happening because things are loaded out of order - i.e. the page attachment is updated before all of the shopping data is loaded (specifically the remote data). 
I'll set some things up with promises so that everything is synced up properly.

2022-04-13 17:53 UTC, processprocess commented
```
page attachment is updated before all of the shopping data is loaded (specifically the remote data).
```

I Think @gmajoulet is suggesting that the store service state should be restored and already have the shopping data. That's how other state properties are restored (like page and attachment state). It would be good to look into why it's not restoring and returning an empty object. Maybe it is restoring but since the example has an empty items data it's throwing the error?

2022-04-13 20:01 UTC, jshamble commented
@processprocess 
I did file a bug for that a few days ago actually (the store service not restoring the data as intended), was going to look into it after this issue was resolved, but I can close that issue and just take care of it as part of this PR.
https://github.com/ampproject/amphtml/issues/38074

2022-04-15 18:11 UTC, closed without merging

2022-04-15 18:11 UTC, jshamble commented
Moved to https://github.com/ampproject/amphtml/pull/38035