Add improvedigital to RTC callout vendors
ampproject/amphtml pull request #38487
Opened 2022-10-11 14:02 UTC by mnishihan

2022-10-11 15:46 UTC, mnishihan commented
I strongly believe - the CircleCI tests, that are failing, are intermittent, caused by networking issues in CircleCI environment & unrelated with the changes in my PR.

For example, [this](https://app.circleci.com/pipelines/github/ampproject/amphtml/26332/workflows/31b1a052-5737-4cc9-96a4-81965bf9a65d/jobs/548565/parallel-runs/0/steps/0-118) & [this](https://app.circleci.com/pipelines/github/ampproject/amphtml/26332/workflows/31b1a052-5737-4cc9-96a4-81965bf9a65d/jobs/548565/parallel-runs/0/steps/0-118) failures are related to PGP key fetching from `keybase.io` and the [other one](https://app.circleci.com/pipelines/github/ampproject/amphtml/26332/workflows/31b1a052-5737-4cc9-96a4-81965bf9a65d/jobs/548568/parallel-runs/0/steps/0-113) also related to some XHR failing.

Also note that, yesterday I opened [another PR](https://github.com/ampproject/amphtml/pull/38484/) with almost identical changes and [all checks](https://github.com/ampproject/amphtml/pull/38484/checks) were passed.

Is there any way, I can rerun the failed tests, or anyone can do so??

TIA

2022-11-01 21:35 UTC, powerivq requested changes

2022-11-01 21:35 UTC, powerivq commented on extensions/amp-a4a/rtc-documentation.md
> +-   [Improve Digital](https://www.improvedigital.com)
Nit: order alphabetically

2022-11-01 22:15 UTC, powerivq commented
As to the failing builds, you might want to try rebasing the latest main if that happens.

2022-11-05 18:34 UTC, mnishihan commented
> As to the failing builds, you might want to try rebasing the latest main if that happens.

@powerivq Done.

2022-11-05 18:39 UTC, mnishihan commented on extensions/amp-a4a/rtc-documentation.md
> +-   [Improve Digital](https://www.improvedigital.com)
Done

2022-11-06 00:24 UTC, powerivq approved these changes

2022-11-06 00:24 UTC, merged