🐛  amp-consent should ignore parameter if not supported by specific command of the tcf api
ampproject/amphtml pull request #38728
Opened 2023-03-30 10:32 UTC by marco-prontera

closes: #36014 

The goal of this PR is to make the handling command logic of the `TcfApiCommandManager` more robust.

The are several vendor that are running in the error described in #36014.
I think this logic could be improved by ignoring the usage of the `parameter` value unless the command is `removeEventListener`.

Plus:
Since these commands support only the version 2, I think we can add a warn and remove also the check of the version value of the `__tcfapiCall` payload and take it for granted if not provided at all. (let me know what you think)

2023-03-30 10:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ampproject/amphtml?pullRequest=38728) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ampproject/amphtml?pullRequest=38728) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ampproject/amphtml?pullRequest=38728) it.</sub>

2023-03-30 10:38 UTC, marco-prontera commented
I saw you are the assignee of the related issue @alanorozco , can you review this PR please?

2023-06-01 08:42 UTC, marco-prontera commented
Hi @erwinmombay, do you have any updates for this review?

2024-01-31 03:24 UTC, erwinmombay commented
@marco-prontera i apologies this didnt get resolved in a timely fashion. I'm looking at this now. my sincere apologies for missing this.

2024-03-06 08:37 UTC, powerivq requested changes

2024-03-06 08:37 UTC, powerivq commented on extensions/amp-consent/0.1/tcf-api-command-manager.js
> +      (!parameter || isNaN(parameter)) &&
I think you would want `parameter === null || isNaN(parameter)` only. isNaN will return true for `undefined`. In opposite, you would want to let `0` pass through, but `!parameter` would treat 0 as false.

2025-07-19 04:19 UTC, closed without merging