✨ create Adsviu as ads vendor
ampproject/amphtml pull request #39063
Opened 2023-05-31 12:46 UTC by Iamlowlo

As an ads vendor, we need to create an AMP version of our widget.
This code adds Adsviu as a valid ads vendor and requests our specific js AMP loader to work with it.

2023-05-31 17:38 UTC, powerivq requested changes
Otherwise LGTM

2023-05-31 17:38 UTC, powerivq commented on 3p/vendors/adsviu.js
> + * Copyright 2021 The AMP HTML Authors. All Rights Reserved.
2023. Here and other files.

2023-06-01 07:28 UTC, Iamlowlo commented on 3p/vendors/adsviu.js
> + * Copyright 2021 The AMP HTML Authors. All Rights Reserved.
Good eye!

2023-06-01 15:00 UTC, Iamlowlo commented
There is a unit test failing (amp-audio-v1.0) that is not relative by far of what this files reach. I don't know if that was a temporary fail, but I cannot relaunch circleCI workflow to check it out. @powerivq

2023-06-01 20:24 UTC, powerivq approved these changes

2023-06-01 23:02 UTC, merged