Fix typos in src/
ampproject/amphtml pull request #39606
Opened 2023-11-08 15:52 UTC by szepeviktor

@powerivq From #39602

See `typos` config in that PR!

2023-11-08 15:56 UTC, szepeviktor commented
Actually I've prepared the 4th PR ...

Here is the `typos` config a willing contributor ⚡ 
```toml
[files]
extend-exclude = [
    ".git/",
    "examples/amp-fx-float-in.html",
    "examples/amp-script/todomvc.ssr.js",
    "examples/amp-script/vue-todomvc.js",
    "examples/amphtml-ads/nws.a4a.html",
    "examples/autocomplete-states.example.json",
    "validator/cpp/htmlparser/casetable.h",
    "validator/cpp/htmlparser/data/CaseFolding.txt",
    "validator/cpp/htmlparser/entity.h",
    "validator/cpp/htmlparser/json/testdata/",
    # Lorem ipsum
    "examples/*.amp.html",
    "examples/amp-toggle-theme.html",
    # Are these downloaded?
    "third_party/",
    "3p/vendors/",
    "ads/vendors/",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    "BUILDing",
    "optin=",
    "to optin to experiments",
    "data.optin;",
    "MEDIA-343ded3e",
    "SYSTEMtaco",
    '"FOO.+"',
    "COM--MENT",
    "splacementMappletfeDistantLightmlfeFloodfeFuncAfeFuncBfeFuncGfeFuncRfeGaus",
    "bang=ba;",
    '"bang", "ba"',
    "cbt=ewIBRj20LWkIv_Xk97MIENbBkf8DGMDAvHsiFWNsZWFubXltYWMubWFjcGF3LmNvbTIICAUTGO27CBRCF2NhLXB1Yi0yNjQwNDcyNzcyMzY4NjQySAZYN2DsA3ABegUIAxIBCA",
    'data-videoid="[^"]"',
    'data-shortcode="[^"]+"',
    # HTML entity
    "&[a-z]+;",
    # Known typo
    "col-fourty",
    # Lorem ipsum
    "libero varius",
    "facilisi morbi",
    "facilisis sed",
    "nulla facilisi",
    "Nam nec",
    "Nam porta",
    "Nam dui",
    "Nam elementum",
    "Nam et magna",
    "Nam finibus",
    "Nam lacinia",
    "Nam molestie",
    "Nam pellentesque",
    "Nam posuere",
    "Nam quam",
    "Nam sit amet",
    "Nulla facilisi",
    "ridiculus mus",
    "varius est",
    "varius libero",
    "varius sem",
    "varius suscipit",
    "varius vitae",
]

[default.extend-words]
# Brand
"adition" = "adition"

[default.extend-identifiers]
# Typos
"Wordpress" = "WordPress"

"amp_stads" = "amp_stads"
"IS_UTF8_TRAIL_2ND_BYTE_VALID" = "IS_UTF8_TRAIL_2ND_BYTE_VALID"
# TODO typo
"BASE_TAG_MUST_PRECEED_ALL_URLS" = "BASE_TAG_MUST_PRECEED_ALL_URLS"
"ValidationError_BASE_TAG_MUST_PRECEED_ALL_URLS" = "ValidationError_BASE_TAG_MUST_PRECEED_ALL_URLS"
# Is it a typo??
"enqueAction" = "enqueAction"
```

2024-02-14 18:53 UTC, erwinmombay approved these changes

2025-04-23 03:24 UTC, szepeviktor commented
@powerivq Friendly ping from the past 🏓

2025-04-23 06:27 UTC, powerivq commented
@szepeviktor You have conflicts needing to be resolved.

2025-04-23 09:38 UTC, szepeviktor commented
Done 🍏

2025-08-10 11:04 UTC, JamBalaya56562 requested changes

2025-08-10 11:04 UTC, JamBalaya56562 commented on src/service/history-impl.js
> +    return this.enqueue_(() => this.binding_.replace(opt_stateUpdate), 'replace');
Thank you for your great work!
However, this line violates prettier format rule.

Could you fix it following [Code quality and style](https://github.com/ampproject/amphtml/blob/main/docs/getting-started-e2e.md#code-quality-and-style) guide?

```bash
amp lint --local_changes --fix
```

2025-08-10 12:46 UTC, szepeviktor commented on src/service/history-impl.js
> +    return this.enqueue_(() => this.binding_.replace(opt_stateUpdate), 'replace');
Done :)

2025-08-12 16:43 UTC, danielrozenberg requested changes

2025-08-12 16:43 UTC, danielrozenberg commented on src/utils/animation.js
> -   * -1: Reset state. Transitionable will be reset to state = 0.
Not a typo, rather our own little invented word :)
Please revert

2025-08-12 16:51 UTC, szepeviktor commented on src/utils/animation.js
> -   * -1: Reset state. Transitionable will be reset to state = 0.
Done 🍏

2025-08-12 18:10 UTC, danielrozenberg commented
Your PR breaks on an unrelated test failure, I just fixed it - can you rebase your PR on `main`? I'll merge it once the tests pass

2025-08-12 18:11 UTC, danielrozenberg approved these changes

2025-08-12 18:16 UTC, szepeviktor commented
@danielrozenberg Rebased 🛩️

2025-08-12 18:35 UTC, merged

2025-08-12 22:23 UTC, szepeviktor commented
Glad to contribute.