Connatix bugfixing
ampproject/amphtml pull request #39696
Opened 2023-12-14 08:39 UTC by cristisilav

- fix mute/unmute controls in the docking interface
- send dock/undock events to the iframe

2023-12-20 19:08 UTC, erwinmombay commented
@cristisilav im trying to reproduce the bug in the examples. would you mind giving me a step by step guide on how to reproduce the bug.

I'm a little hesitant if the mutation observer approach here is the way to go do observe docking. trying to see if there is a low level event that we can programmatically listen to instead

cc @powerivq

2023-12-20 21:50 UTC, erwinmombay commented
also a heads up that we are currently in code freeze and will exit out of the freeze first week of January

2024-01-03 09:27 UTC, cristisilav commented
> @cristisilav im trying to reproduce the bug in the examples. would you mind giving me a step by step guide on how to reproduce the bug.
> 
> I'm a little hesitant if the mutation observer approach here is the way to go do observe docking. trying to see if there is a low level event that we can programmatically listen to instead
> 
> cc @powerivq

Regarding the bug, the issue was that the mute/unmute control in the docking interface would not always reflect the actual volume of the player, which happened because I didn't explicitly emit that mutedOrUnmutedEvent.
As for docking observing, I couldn't find any event that was emitted (outside of obvious options such as a transitionstart or animationstart). By any chance have you found any other reliable, docking-specific events? Thank you!

2024-01-03 22:23 UTC, powerivq requested changes

2024-01-03 22:23 UTC, powerivq commented on extensions/amp-connatix-player/0.1/amp-connatix-player.js
> +    const observer = new MutationObserver(callback);
Can you move the observer to a member property. When the player is being destroyed, we can clean up the observer.

2024-01-03 22:51 UTC, erwinmombay commented
@cristisilav I talked with @powerivq and we couldn't find a low level event to listen to, so lets go ahead and proceed with this change with the minor request that @powerivq asked for and we can merge this

2024-01-09 18:20 UTC, erwinmombay approved these changes

2024-01-09 20:44 UTC, erwinmombay commented
@cristisilav could you rebase from main to fetch the latest updates. i think that should fix the circle ci/test failure

2024-01-10 19:03 UTC, powerivq approved these changes

2024-01-10 19:16 UTC, merged