✨ Vendor Registration: Integrating BidGear Ad Networks into amp-ad
ampproject/amphtml pull request #39946
Opened 2024-04-04 10:14 UTC by tindvubg

✨ Vendor Registration: Integrating BidGear ad networks into AMP
For more than 8 years, BidGear has been transforming the way marketing is conducted for Brands and Consumers. Through real-time bidding, yield management, and workflow automation, BidGear enables publishers and media buyers to evaluate the attributes of each impression to determine its precise value, optimizing yield and maximizing revenue. We have seen strong growth of the AMP web platform, so we want to expand the AMP advertising platform to provide monetization opportunities for advertising partners, web developers, and users. Therefore, we would like to ask you to please approve us as soon as possible so that we can quickly participate in the advertising market on AMP. 
Thank you!

2024-04-04 10:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ampproject/amphtml?pullRequest=39946) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ampproject/amphtml?pullRequest=39946) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ampproject/amphtml?pullRequest=39946) it.</sub>

2024-04-08 03:51 UTC, tindvubg commented
@calebcordry Please support me!

2024-04-12 04:16 UTC, powerivq requested changes

2024-04-12 04:16 UTC, powerivq commented on ads/_config.js
> +
Nit: please order it alphabetically.

2024-04-12 04:16 UTC, powerivq commented on examples/ads.amp.html
> +<!doctype html>
What is this file used for? I think you might want to remove this file.

2024-04-12 04:31 UTC, powerivq requested changes

2024-04-12 04:31 UTC, powerivq commented on ads/_config.js
> +
Nit: remove this newline (line 1581)

2024-04-12 05:12 UTC, powerivq approved these changes

2024-04-12 05:54 UTC, powerivq commented
Need to fix the lint error: https://app.circleci.com/pipelines/github/ampproject/amphtml/30644/workflows/1ead9dfc-009f-4b9e-bee6-40527f919b47/jobs/661308?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary

2024-04-12 09:44 UTC, tindvubg commented
> Need to fix the lint error: https://app.circleci.com/pipelines/github/ampproject/amphtml/30644/workflows/1ead9dfc-009f-4b9e-bee6-40527f919b47/jobs/661308?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary

I have fixed it. Please let me know what I should do next. Thank you! @powerivq

2024-04-16 22:51 UTC, merged