✨ Update path for openadstream ads url
ampproject/amphtml pull request #40091
Opened 2024-07-17 06:00 UTC by HJK51

You can add the url path of the OAS ad tag.

# References:
- AMP code contribution docs: go.amp.dev/contribute/code
- First time setup (required for CI checks): go.amp.dev/getting-started

2024-07-17 06:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ampproject/amphtml?pullRequest=40091) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ampproject/amphtml?pullRequest=40091) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ampproject/amphtml?pullRequest=40091) it.</sub>

2024-07-24 19:45 UTC, erwinmombay commented
@powerivq could you take a look at this?

2024-07-24 20:32 UTC, powerivq requested changes

2024-07-24 20:32 UTC, powerivq commented on ads/vendors/openadstream.js
> +import {validateData, writeScript } from '#3p/3p';
Nit: space

2024-07-31 17:48 UTC, powerivq commented
Hey @HJK51 can you change that to fix the PR?

2025-04-14 21:07 UTC, powerivq commented
My understanding is that there is another PR.

2025-04-14 21:07 UTC, closed without merging